#include "node.h"
#include "list.h"
#include "text_list.h"
#include "answer.h"
#include "task.h"
#include "unit.h"

#include "node.cpp"
#include "list.cpp"
#include "text_list.cpp"
#include "answer.cpp"
#include "task.cpp"
#include "unit.cpp"